### ISSUE TITLE
[🐞]: Create compat missing textures & language keys

### ISSUE THREAD

**Issue by VoidLeech** [MehVahdJukaar/StoneZone#13] opened 2024-12-21 13:25 UTC
### Code of Conduct

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Ensure the version of EveryCompat & Moonlight Lib are up to date
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version - Loader (DO NOT FORGET TO SELECT THE CORRECT VERSION)

1.20.1 - FORGE

### StoneZone Version

stonezone-1.20-2.7.1

### Moonlight Lib Version

moonlight-1.20-2.13.41

### Issue with mods

Create 0.5.1j

Certain stone mods, such as
Deeper and Darker
Quark
Naturalist
And more D:

### Issue Detail

The language key is incorrect for the cut brick stairs, cut brick slab, and cut brick wall, the actual id has `brick`, not `bricks`: 
https://github.com/MehVahdJukaar/StoneZone/blob/aa0765d7afd98ba957a5e405e8129476c6562e46/common/src/main/resources/assets/stonezone/lang/en_us.json#L25-L27
![image](https://github.com/user-attachments/assets/14ab088c-d702-4b94-9bc4-2b69c822c4dc)

Certain block variants (not all) for stone types from certain mods (not all) will have missing textures for *some* of their faces: 
![image](https://github.com/user-attachments/assets/39f36503-4b71-41c2-861b-d9afd1eb58ca)

The only such cases I encountered were when the stone mod already added a:
- TYPE_pillar (the layered_TYPE would then miss its top and bottom faces)
- cut_TYPE_slab (the polished_cut_TYPE_slab would then miss its side faces) 

But I assume there might be more scenarios where one stonezone block uses the textures generated from a different stonezone block that didn't get registered because the stone mod already has a block matching that name pattern.

**Comment by Xelbayria** [comment] 2024-12-21 18:54
Try v2.7.2 and let me know if the issue is resolved. (it will take a while for the version to get approval on Curseforge)

**Comment by Xelbayria** [comment] 2024-12-21 19:22
there was a typo in EN_US for the missing lang key. it's resolved in v2.7.3

**Comment by Xelbayria** [comment] 2024-12-21 19:23
## FIXED in v2.7.2 - Missing Textures

---

## FIXED in v2.7.3 - Missing key langs

**Comment by VoidLeech** [comment] 2024-12-21 22:29
Yep textures are fixed. Looks like a c/stone_mod/type_pillar is made even if the stone mod already has a type_pillar (or if both furniture mod and stone mod add a type with the same name), but from your commits that looks intended.

I am seeing a lot less stone types getting detected (some that indeed did not seem like stone types, which yeah I wouldn't consider that an issue, but also some that did seem like stone types) than before though, but I'll go make a separate issue for that. (Probably tomorrow though)

**Comment by Xelbayria** [comment] 2024-12-21 22:48
Alright, 

if you find some undetected stoneTypes. I'll need the ID of that stoneTypes, so i can manually add it. 

you are correct, it was intended because there are too many stoneTypes from **Chipped** and **Create** that shouldn't be included 

Can i get the stone_mod, so i can take a look

**Closed** 2024-12-22 06:24 UTC
Labels: bug, 1.20.1-FORGE
